--- 

- name: Set Debian audit grub cmdline
  ansible.builtin.lineinfile:
    line: 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX {{ hardening_audit_grub_cmdline }} {{ hardening_audit_grub_backlog_cmdline }}"'
    dest: /etc/default/grub.d/99-hardening-audit.cfg
    state: present
    create: 'yes'
    mode: 0755
    owner: root
    group: root
  when: ansible_os_family == "Debian"
  become: true

- name: Set RedHat audit grub cmdline
  ansible.builtin.command: 'grubby --update-kernel=ALL --args="{{ hardening_grub_audit_cmdline }} {{ hardening_grub_audit_backlog_cmdline }}"'
  register: grubby_update_kernel
  when: ansible_os_family == "RedHat"
  changed_when: grubby_update_kernel.rc != 0
  failed_when: grubby_update_kernel.rc != 0
  become: true

- name: Install auditd package
  ansible.builtin.package:
    name: '{{ hardening_auditd_package }}'
    state: 'present'
  become: true

- name: Configure auditd 
  ansible.builtin.template:
    src: 'etc/audit/auditd.conf.j2'
    dest: '/etc/audit/auditd.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'
  notify: 'Restart auditd'
  become: true

- name: Configure audit.rules
  ansible.builtin.template:
    src: etc/audit/rules.d/hardening.rules.j2
    dest: /etc/audit/rules.d/hardening.rules
    backup: 'yes'
    mode: 0600
    owner: root
    group: root
  notify: 'Restart auditd'
  become: true

