--- 
- name: disable ctrl-alt-del
  ansible.builtin.systemd:
    name: ctrl-alt-del.target
    masked: 'yes'
    enabled: 'no'
    state: stopped
  when: not ansible_os_family == "RedHat"
  become: true
  ignore_errors: true

- name: disable ctrl-alt-del - idempotence
  ansible.builtin.systemd:
    name: ctrl-alt-del.target
    masked: 'yes'
    enabled: 'no'
    state: stopped
  when: ansible_os_family == "RedHat"
  changed_when: false
  become: true
