---
- name: Add nameserver to resolv.conf
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/resolv.conf
    line: "nameserver {{ item }}"
    mode: 0644
    owner: root
    group: root
    state: present
  with_items: "{{ dns | split }}"