---
- name: Create custom facts directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    recurse: true
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Set systemd version fact
  ansible.builtin.template:
    src: etc/ansible/facts.d/systemd.fact
    dest: /etc/ansible/facts.d/systemd.fact
    mode: 0755
    owner: root
    group: root
  become: true

- name: Set cpuinfo rdrand fact
  ansible.builtin.template:
    src: etc/ansible/facts.d/cpuinfo.fact
    dest: /etc/ansible/facts.d/cpuinfo.fact
    mode: 0755
    owner: root
    group: root
  become: true

- name: Set ssh keys fact
  ansible.builtin.template:
    src: etc/ansible/facts.d/sshkeys.fact
    dest: /etc/ansible/facts.d/sshkeys.fact
    mode: 0755
    owner: root
    group: root
  become: true

- name: Update facts
  ansible.builtin.setup: ~
