---
# tasks file for ansible_hardening
- name: Fetch OS dependent variables
  include_vars:
    file: '{{ item }}'
    name: 'os_vars'
  with_first_found:
    - files:
        - '{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml'
        - '{{ ansible_facts.distribution }}.yml'
        - '{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml'
        - '{{ ansible_facts.os_family }}.yml'
      skip: true
  tags: always

- name: Set OS dependent variables, if not already defined by user
  set_fact:
    '{{ item.key }}': '{{ item.value }}'
  when: "not lookup('varnames', '^' + item.key + '$')"
  with_dict: '{{ os_vars }}'
  tags: always

- ansible.builtin.include_tasks: facts.yml
- ansible.builtin.include_tasks: dns.yml
- ansible.builtin.include_tasks: pre.yml

# - ansible.builtin.include_tasks: firewall.yml
#   tags: firewall
#   when: firewall_enabled | bool

- ansible.builtin.include_tasks: auditd.yml
  tags: auditd
  when: auditd_enabled | bool

# - ansible.builtin.include_task: cron.yml
#   tags: cron
#   when: cron_enabled | bool