---
# tasks file for ansible_hardening
- name: Fetch OS dependent variables
  include_vars:
    file: '{{ item }}'
    name: 'os_vars'
  with_first_found:
    - files:
        - '{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml'
        - '{{ ansible_facts.distribution }}.yml'
        - '{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml'
        - '{{ ansible_facts.os_family }}.yml'
      skip: true
  tags: always

- name: Set OS dependent variables, if not already defined by user
  set_fact:
    '{{ item.key }}': '{{ item.value }}'
  when: "not lookup('varnames', '^' + item.key + '$')"
  with_dict: '{{ os_vars }}'
  tags: always

- ansible.builtin.include_tasks: facts.yml
- ansible.builtin.include_tasks: dns.yml
- ansible.builtin.include_tasks: pre.yml
- ansible.builtin.include_tasks: auditd.yml
- ansible.builtin.include_tasks: aide.yml
- ansible.builtin.include_tasks: cron.yml
- ansible.builtin.include_tasks: sysctl.yml
- ansible.builtin.include_tasks: disablemodules.yml
- ansible.builtin.include_tasks: ctrlaltdel.yml
- ansible.builtin.include_tasks: limits.yml
- ansible.builtin.include_tasks: journalconf.yml
- ansible.builtin.include_tasks: users.yml
# - ansible.builtin.include_tasks: timesyncd.yml

# - ansible.builtin.include_tasks: firewall.yml
#   when: firewall_enabled | bool

# - ansible.builtin.include_tasks: ipv6.yml
#   when: disable_ipv6 | bool


